name: PyPI CloudArtifact Action Demo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            python -m pip install --upgrade twine
            twine --version
            ls -al


#             python -m pip install --upgrade build
#             python -m build
#             ls -al
# #           python3 --version
#           python --version
#           pip --version
#           pip3 --version
#           pip install twine
#           mkdir -p ~/.pip
#           mv pip.conf ~/.pip/pip.conf
#           pip install demo==1.0
#         twine --version
#         mv .pypirc  ~/.pypirc
#         cat ~/.pypirc
#         python setup.py bdist_wheel bdist_egg  sdist
#         ls -al dist/
#         twine upload -r pypi dist/*
